version: "3.7"
services:
  lb:
    build:
      context: .
      dockerfile: Dockerfile_LB
    ports:
      - "80:80"
    environment:
      PORT: 80
    networks:
      - pwr9
  ui:
    build:
      context: pwr9-ui
      dockerfile: Dockerfile
    ports:
    - "8001:80"
    environment:
      PORT: 80
    networks:
      - pwr9
  cache:
    image: redis:5-buster
    ports:
      - "6379:6379"
    networks:
      - pwr9
  warm_cache:
    depends_on:
      - cache
    build:
      context: pwr9-api
      dockerfile: Dockerfile-warm
    environment:
      REDIS_URL: cache
    networks:
      - pwr9
  api:
    build:
      context: pwr9-api
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      REDIS_URL: cache
    networks:
      - pwr9
networks:
  pwr9: